{% set version = "0.16.0" %}

package:
  name: adcc
  version: {{ version }}

source:
  url: https://github.com/adc-connect/adcc/archive/v{{ version }}.tar.gz
  sha256: 2bf56637f151642b5d9cc7cda99f27ed3781226e7e12ae4c308ea3cd1d49c43e

build:
  number: 0
  skip: true  # [win or ppc64le]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkgconfig
    - wget
  host:
    - python
    - setuptools
    - pip
    - libtensorlight >=3.0.1
    - pybind11 >=2.6
  run:
    - python
    - setuptools
    - numpy >=1.14
    - h5py >=2.9
    - scipy >=1.2
    - tqdm >=4.30
    - opt_einsum >=3.0

test:
  requires:
    - pytest
    - pip
    - pyscf
  imports:
    - adcc
  commands:
    - export PYLIB_EXT=`$PYTHON -c 'import sysconfig as s; print(s.get_config_var("EXT_SUFFIX"))'`
    - test -f $SP_DIR/libadcc$PYLIB_EXT
    - test -f $SP_DIR/adcc/AdcMethod.py
    - pytest --pyargs adcc -v

about:
  home: https://adc-connect.org
  dev_url: https://github.com/adc-connect/adcc
  doc_url: https://adc-connect.org
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: 'adcc: Seamlessly connect your program to ADC'
  description: |
    adcc (**ADC-connect**) is a python-based framework for performing
    the calculation of molecular spectra and electronically excited states
    based upon the algebraic-diagrammatic construction (ADC) approach.
    Arbitrary host programs may be used to supply a
    self-consistent field (SCF) reference to start off the ADC calculation.
    Currently adcc comes with ready-to-use interfaces to four programs,
    namely pyscf, psi4, VeloxChem or molsturm. Adding other SCF codes or
    starting a calculation from
    statically computed data can be easily achieved.

extra:
  recipe-maintainers:
    - maxscheurer
